# Generated by Django 5.1.1 on 2024-10-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_address_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='post_Code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
